export const animatorObj = {
  anim1: [{ transform: "rotateX(0)" }, { transform: "rotateX(720deg)" }],
  anim2: [{ top: "-1rem" }, { top: "1rem" }],
  anim3: [{ left: "1rem" }, { left: "-1rem" }],
  anim4: [{ border: "1px solid transparent" }, { border: "5px solid transparent" }],
  anim5: [
    { top: `${Math.floor(Math.random() * 10)}rem` },
    { transform: "rotateX(0)" },
    { top: "10rem" },
    { right: "5rem" },
    { top: `${Math.floor(Math.random() * 10)}rem` },
    { bottom: `${Math.floor(Math.random() * 10)}rem` },
    { right: "10rem" },
    { left: `${Math.floor(Math.random() * 10)}rem` },
    { left: "-10rem" },
    { bottom: `${Math.floor(Math.random() * 10)}rem` },
    { bottom: `${Math.floor(Math.random() * 5)}rem` },
    { right: "10rem" },
    { left: "5rem" },
    { left: "10rem" },
    { right: `${-Math.floor(Math.random() * 20)}rem` },
    { left: `${Math.floor(Math.random() * 10)}rem` },
    { transform: "rotateX(720deg)" },
  ],
  anim6: [
    { right: `${Math.floor(Math.random() * 10)}rem` },
    { botom: "10rem" },
    { left: "5rem" },
    { transform: "rotateX(0deg)" },
    { top: `${-Math.floor(Math.random() * 10)}rem` },
    { bottom: `${Math.floor(Math.random() * 10)}rem` },
    { bottom: "10rem" },
    { top: `${Math.floor(Math.random() * 10)}rem` },
    { left: "10rem" },
    { left: `${-Math.floor(Math.random() * 10)}rem` },
    { bottom: `${Math.floor(Math.random() * 5)}rem` },
    { right: "10rem" },
    { transform: "rotateX(360deg)" },
    { left: "5rem" },
    { left: "-10rem" },
    { top: `${Math.floor(Math.random() * 20)}rem` },
    { left: `${Math.floor(Math.random() * 10)}rem` },
  ],
  time: {
    duration: 1000,
    iterations: 1,
  },
};
